Initial commit of ceasar chiper with tests
StefanGajic/Rotational-Cipher pull request #2
Opened 2020-06-29 19:47 UTC by StefanGajic

Initial commit with added .gitignore

2020-06-29 21:29 UTC, basti commented on lib/rotational_cipher.rb
> +    ALPHABET = ("a".."z")
@StefanGajic constants are most often defined at the beginning of the class. Go through the Ruby style guide and consult it whenever in doubt. In this case take a look at the general class structure: https://rubystyle.guide/#consistent-classes

2020-06-29 21:29 UTC, basti commented on lib/rotational_cipher.rb
> +    attr_reader :text, :number
@StefanGajic a lot of things in Ruby are guided by convention. One of them is that the code should be easily understandable. In this case, I have no clue what text or number is, I only know what type they should be.

Instead, try using descriptive names. Like: message, original_message, rot_number, rotate_key, key... or similar.

Additionally, there's a question - do you need to expose these attributes? I don't see you using them anywhere in the code.

2020-06-29 21:29 UTC, basti commented on lib/rotational_cipher.rb
> +
@StefanGajic unnecessary blank line. Again go through Ruby style guide for general guidance on Ruby code styling.

2020-06-29 21:29 UTC, basti commented on lib/rotational_cipher.rb
> +
@StefanGajic blank line.

2020-06-29 21:29 UTC, basti commented on lib/rotational_cipher.rb
> +        text.each_char do |i|
@StefanGajic similar to attribute names... try using descriptive names. Single-letter names like i, j, k are allowed only in small iteration blocks. Here a better name would be `current_char`, `character`, or even `c` would be ok since this is a small block.

2020-06-29 21:29 UTC, basti commented on lib/rotational_cipher.rb
> +                number.times {i = i.next}
@StefanGajic avoid changing the iteration/loop var within the block. If you have to change it, assign it to another local var.

Also, this is an interesting solution, but we'll get into that later.

Finally styling: https://rubystyle.guide/#spaces-braces

2020-06-29 21:29 UTC, basti commented on lib/rotational_cipher.rb
> +            if ALPHABET.include? (i.downcase)
@StefanGajic don't use space between a method name `include?` and its arguments.

2020-06-29 21:42 UTC, basti requested changes
@StefanGajic let's start with these mostly style-related changes. Then we'll move on to the algorithm, tests, and trying it out.

Also, be aware that I am going to force some OOP concepts into these assignments even though they are an overkill for this simple task - just bear with me.

2020-06-29 21:42 UTC, basti commented on lib/rotational_cipher.rb
> +        cipher << i[-1]
@StefanGajic bad indentation.

2020-06-29 21:42 UTC, basti commented on lib/rotational_cipher.rb
> + end
@StefanGajic files should have a new line at the end. Even Github marks files without it with a special sign. See: https://thoughtbot.com/blog/no-newline-at-end-of-file

You can configure your editor to automatically add it. While you are at it you can set it to trim whitespace (if it doesn't do that already).

2020-06-29 21:42 UTC, basti commented on lib/rotational_cipher.rb
> +    def caesar_cipher
@StefanGajic naming. So this would be `CeasarCipher.new(arg1, arg2).ceasar_cipher`? Try renaming it to something more readable and without duplication.

2020-06-29 21:42 UTC, basti commented on lib/rotational_cipher.rb
> +class CeasarChiper
@StefanGajic not to nitpick, but:

>ROT13 is a special case of the Caesar cipher which was developed in ancient Rome.

(from https://en.wikipedia.org/wiki/ROT13).

This class allows any type of ROT encryption, not just ROT13 a.k.a. Ceasar cipher.

Also, the class name and file name should match in most of the cases. Often it's used to automatically guess file name for the class you want to load. `CeasarChiper` should be in `ceasar_chiper.rb` and `rotational_cipher.rb` should contain `RotationalCipher`.

2020-06-30 11:27 UTC, StefanGajic commented on lib/rotational_cipher.rb
> +    attr_reader :text, :number
I am using them in `initialize` and `caesar_cipher` method

2020-06-30 11:39 UTC, basti commented on lib/rotational_cipher.rb
> +    attr_reader :text, :number
@StefanGajic you are right about `caesar_cipher`, but you are not using it in `initialize`. For now, can you please use instance vars directly in `caesar_cipher`?

2020-06-30 16:35 UTC, basti requested changes

2020-06-30 16:35 UTC, basti commented on lib/rotational_cipher.rb
> +
@StefanGajic unnecessary blank line.

2020-06-30 16:35 UTC, basti commented on spec/rotational_cipher_spec.rb
> +      end
@StefanGajic indentation is off in this whole section. Please check.

2020-06-30 16:35 UTC, basti commented on lib/rotational_cipher.rb
> +      cipher << c[-1]
@StefanGajic why are you using -1 here? How is it different than using `c[0]` or `c`?

2020-06-30 16:35 UTC, basti commented on main.rb
> +if input_number <= 26
@StefanGajic validating input in the script is ok, but the class should do its own validations too. What if I was using RotationalCipher in my program and I called it with a number higher than 26?

2020-06-30 16:35 UTC, basti commented on main.rb
> +  puts rc.encrypt
@StefanGajic can you please modify the main.rb script to allow encrypting more strings than one? After the first string is encrypted, ask me to enter another string.

Also as an additional assignment can you make a `main-cli.rb` which could be used as a command line program. I would like to be able to do something like `ruby main-cli.rb 13 Text to encrypt` or similar.

2020-06-30 16:35 UTC, basti commented on lib/rotational_cipher.rb
> +        @rot_number.times { c = c.next }
@StefanGajic if you have 1KB of data, i.e. 1024 characters with ROT25... how many iterations are needed to get everything encrypted? This is an elegant solution, but not really optimized.

Also, please avoid changing the so-called index/value var in the iterator. You probably won't mess up the loop/iterator, but you might confuse other people looking at the code. If you want to change it assign it first to another local variable.

2020-06-30 16:35 UTC, basti commented on lib/rotational_cipher.rb
> +  def initialize(original_message, rot_number)
@StefanGajic if you imagine RotationalCipher as a machine it would make sense for the operator to set the encryption key (i.e. rot_number) and then feed letters to it to get the encrypted ones - right? So in a way, the only state of that machine is the rot_number setting. Everything else can be forgotten after encryption is done.

This would allow you to create more robust and reusable objects and you could do this:

```
rot13 = RotationalCipher.new(13)
rot1 = RotationalCipher.new(1)

messages.each do |message|
  puts "Original: #{message}" 
  puts "ROT1: #{rot1.encrypt(message)}"
  puts "ROT13: #{rot13.encrypt(message)}"
end
```

This would be hard with the current setup. Please change it so the code above is possible.

2020-06-30 17:33 UTC, StefanGajic commented on lib/rotational_cipher.rb
> +      cipher << c[-1]
using `c[0]` or just `c` is not working properly. It is because of the last character in the string, example encrypt of 'z' 2 times with `c[0]` is 'a'. And with `c` is 'ab'. While with` [-1]` gives correct result of 'b'

2020-07-01 06:02 UTC, StefanGajic commented on main.rb
> +  puts rc.encrypt
I am looking at [this link](https://stackoverflow.com/questions/13225762/pass-value-with-space-to-ruby-script) for `Text to encrypt` in `main-cli.rb` Hope its fine to use double quotes` "` in between the text user wants to encrypt because it says command line parser need either double quotes or ` \` after each word to successfully encrypt text with spaces.

2020-07-01 08:11 UTC, basti commented on main.rb
> +  puts rc.encrypt
Using double quotes is ok - as SO answer said it's not a Ruby issue, it's how the terminal works.

2020-07-01 08:15 UTC, basti commented on lib/rotational_cipher.rb
> +      cipher << c[-1]
Ok, close enough. I wanted to see your understanding of how `next` works. I never used it before and was surprised when I saw in https://ruby-doc.org/core-2.6/String.html#method-i-next that `"abc".next => "abd"`. Also, -1 on an array-like object usually returns the last element.

2020-07-03 08:56 UTC, basti requested changes
@StefanGajic only a couple smaller suggestions. Otherwise, I think this is it. Let me know once you are done with this to send you the new assignment.

2020-07-03 08:56 UTC, basti commented on lib/rotational_cipher.rb
> +  def valid_number?
@StefanGajic where is this method used?

2020-07-03 08:56 UTC, basti commented on lib/rotational_cipher.rb
> +      @valid_number = false
@StefanGajic usually in cases like these there is no point in continuing with object creation, especially because the resulting object will be unusable. So it makes sense to raise an exception. The ideal exception, in this case, would be `ArgumentError` (https://ruby-doc.org/core-2.7.1/ArgumentError.html) with an added appropriate message.

This means that the caller must be able to handle the possible exception.

2020-07-03 08:56 UTC, basti commented on lib/rotational_cipher.rb
> +      end
@StefanGajic again an interesting solution. I like the fact that loops are gone or at least hidden into `include?` and `index`. I do have a suggestion on how to get rid of `include?` call: use the `index` method instead - it returns [int or nil](https://ruby-doc.org/core-2.7.1/Array.html#method-i-index).

```suggestion
      if index = LOW_ALPHABET.index(char)
        shift = (index + @rot_number) % MAX_NUMBER
        cipher << LOW_ALPHABET[shift]
      elsif index = HIGH_ALPHABET.index(char)
        shift = (index + @rot_number) % MAX_NUMBER
        cipher << HIGH_ALPHABET[shift]
      else
        cipher << char
      end
```

2020-07-03 14:58 UTC, basti approved these changes

2020-07-03 14:58 UTC, basti commented on lib/rotational_cipher.rb
> +      @valid_number = true
@StefanGajic I assume this is not needed too.

2020-07-03 15:05 UTC, merged